### ISSUE TITLE
lobster-python: false positive on duplicate function definition

### ISSUE THREAD

**Issue by jnow-87** [bmw-software-engineering/lobster#36] opened 2024-04-30 13:26 UTC
lobster-python reports a duplicated function definition for `severity()` in the following example:
```
import dataclasses

@dataclasses.dataclass
class Diagnostic: 
    _severity: int = dataclasses.field()

    @property
    def severity(self):
        return self._severity

    @severity.setter
    def severity(self, value: int):
        self._severity = value
```

These are clearly not duplicate functions but separate ones which can both be called on the same instance if Diagnostic. Hence, this case should be fixed within lobster.

The problem might originate from here https://github.com/bmw-software-engineering/lobster/blob/6bb274e19b47b8ced6fc9c6d103c5e4418cf83a7/lobster/tools/python/python.py#L197-L198 since the function tag is built only using `self.fqn()`, which is probably the function name. A solution might be to consider the entire function signature as the tag.

**Comment by phiwuu** [comment] 2024-04-30 16:04
Possible duplicate of https://github.com/bmw-software-engineering/lobster/issues/30

**Closed** 2024-07-29 07:38 UTC
Labels: lobster-core, lobster-python
